### ISSUE TITLE
Has not been tested in years, will test soon, and attempt to finish it.

### ISSUE THREAD

**Issue by JihadiJackass** [JihadiJackass/JihadiModPack-PS3-Fallout-New-Vegas#1]
as title says, I will adjust this soon.

**Comment by Cris118** [comment]
Any luck?

**Comment by JihadiJackass** [comment]
> Any luck?

Haven't pulled out my PS3 yet but I will today, I'll reply soon

**Comment by Cris118** [comment]
> Haven't pulled out my PS3 yet but I will today, I'll reply soon

Any progress?

**Comment by JihadiJackass** [comment]
Yes, I will post an update soon, been a bit busy lately.

**Comment by Cris118** [comment]
Don't worry, take your time.

**Comment by Cris118** [comment]
hey, I saw in a page about fo3 modding on ps3 something about creating a DDX file to be able to add custom textures, does that ring any bells for you?

**Comment by Cris118** [comment]
Also this:

"You can make the game force load .DDS files by adding 'bUseDDX=0' to the general section of fallout.ini, however the draw back to this method is that ONLY .DDS files will load and not .DSX files so you have to replace all the .DSX Files from the game with the .DDS files from the PC version of the game. And even then some of the textures may not even load properly, saving and reloading seems to help but only temporarily."

**Comment by noahsshitbird** [comment]
This seems awesome, he might have gotten into school or got a job and not have as much time.

**Comment by noahsshitbird** [comment]
I did find something that might be a fix for the meshes and textures not loading but idk any of this kind of stuff. https://taleoftwowastelands.com/viewtopic.php?t=8112

**Comment by JihadiJackass** [comment]
Hey guys, sorry for the delayed response. Been focusing on my health lately. I'll get back to this asap.

> Also this:
> 
> "You can make the game force load .DDS files by adding 'bUseDDX=0' to the general section of fallout.ini, however the draw back to this method is that ONLY .DDS files will load and not .DSX files so you have to replace all the .DSX Files from the game with the .DDS files from the PC version of the game. And even then some of the textures may not even load properly, saving and reloading seems to help but only temporarily."

I will look into this :D

**Comment by Cris118** [comment]
if there is anything I can help you with pls tell me

**Comment by JihadiJackass** [comment]
> if there is anything I can help you with pls tell me

I am testing various methods currently, but so far it is not looking good.

Without JIP, or NVSE, it is quite impossible to control anything meaningful.

Do you have any prior experience in this @Cris118?

**Comment by Cris118** [comment]
Just offering assistance in general (sorry for the late response)

**Comment by JihadiJackass** [comment]
Cannot resolve this issue, I will update the mod with some improvements that I have worked on, but in general, I cannot do much here.

If anyone would like to request specific mod packs, I can do this somewhat.

Thanks for the interest guys ❤️
